### ISSUE TITLE
Unlinks as points do not unlink

### ISSUE THREAD

**Issue by laurensversluis** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#107]
I have a spatial model with the unlinks represented as points. Verification steps show no errors. Processing using segment analysis. Processed map just segments the disconnected lines thus does not unlinking them. 

![image](https://cloud.githubusercontent.com/assets/11682704/8106435/39b005c2-1039-11e5-9ed8-78410c1623d0.png)

**Comment by jorgegil** [comment]
The unlinks ID update is assigning the wrong ID to lines 1 and 2.
