### ISSUE TITLE
DepthmapXnet-0-30.exe crash after starting process.

### ISSUE THREAD

**Issue by laurensversluis** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#121]
Latest version of esstookit (0.5) crashes DepthnetXnet-0-30 when trying to process.

**Comment by jorgegil** [comment]
It needs the latest version of depthmapXnet that removes stubs. Here's a temporary link for testing:
https://www.dropbox.com/s/maai88714okfgpi/depthmapXnet-0.30v2-Windows.zip?dl=0

**Comment by jorgegil** [comment]
Is it DepthmapXnet-0-30 from July 2014?
Can you send me a link to the file so I can replicate your error? It runs with the sample data.
Thanks

**Comment by laurensversluis** [comment]
I verified the model. Because it takes long I usually skip this step. Apparently the model had duplicated geometry, some islands and small lines. After that is actually worked. So perhaps its more me than the program ;)

**Comment by jorgegil** [comment]
What file format are you using? Verification is slow with shape files, but can be very fast with spatialite and postgis, at least on my tests.
Even if the map has errors, it should not just crash. I'll try to process maps with errors to see if this bug happens.
