### ISSUE TITLE
Docks incorrectly displayed on Gnome3

### ISSUE THREAD

**Issue by pcav** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#123]
See attached

**Comment by pcav** [comment]
![plugin](https://cloud.githubusercontent.com/assets/691842/8546541/ff2852e4-24b8-11e5-84c1-2ac2c963c26e.png)

**Comment by jorgegil** [comment]
I've been unable to reproduce the problem on an Ubuntu Gnome3 VM.
Made some changes to the docks initialisation, now with Gui init and not on main init, possibly fixes the problem. The latest upload includes this change.

**Comment by pcav** [comment]
Thanks. I do not see a new version though.

**Comment by jorgegil** [comment]
I've uploaded a new zip file to the first version. Sorry, maybe I should have made a new version instead...

**Comment by pcav** [comment]
Yes, better having new versions: could you please fix this?
Thanks.

**Comment by jorgegil** [comment]
I've created a new version with the updated package. Thanks for checking this.
