### ISSUE TITLE
Model does not process in POSTGIS

### ISSUE THREAD

**Issue by laurensversluis** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#124]
Processing a model within a PostGIS directory starts but does not progress.

QGIS 2.8.2
ESSToolkit 0.0.5
DepthNetX 0.3b

**Comment by jorgegil** [comment]
Hi Laurens,
I've tested on a local and a remote server, and couldn't reproduce your problem. Could you please send me a data sample to see what might be causing it?

**Comment by laurensversluis** [comment]
Just tried it on 0.1 and it worked! Unfortunately the status bar does not update incrementally so you don't know when it will finish.

**Comment by jorgegil** [comment]
I suspect it's an issue with the post processing of the analysis, the progress bar updates incrementally only up to there. Saving to a PostGIS remote server seems to be quite slow at the moment...
