### ISSUE TITLE
Is there any tutorial or plugin manual somewhere ?

### ISSUE THREAD

**Issue by simogeo** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#127]
Is there any tutorial or plugin manual somewhere ?

Thanks

**Comment by jorgegil** [comment]
The user guide for the latest version can be found in the documents folder.
There you also find a workshop presentation given in July, which to some extent explains the plug-ins workflow as in a tutorial.
A more detailed step-by-step tutorial needs to be developed at some point...

**Comment by simogeo** [comment]
Many thanks for pointing me out documentation. Actually, I think it would be great - and quite easy - to add link to documentation (or embedding it) into the QGIS plugin itself !  At least to the quick start guide

**Comment by simogeo** [comment]
By the way, is there a doc explaining all new depthmap generated attributes  : CHR, INT, TD, NACH and so on .... ?

**Comment by jorgegil** [comment]
Thanks for the suggestion, I'll look into better integration of the user guide in a future version of the tool.

As for those new attributes, p.16 explains what depthmap measure the acronym stands for. What each measure calculates and means should be found in the Depthmap user manual and tutorials, the space syntax training platform (http://otp.spacesyntax.net/), and the space syntax methodologies textbook (http://discovery.ucl.ac.uk/1415080/).
I'll add these links to the user guide.

**Comment by rtsaboya** [comment]
Perhaps we could create the documentation collaboratively? This would alleviate the burden of the programmer(s) and let them focus on more specialized tasks. If you have any guidance on how we could go about it, I could try to help.

Congratulations for this amazing plugin!

**Comment by jorgegil** [comment]
@rtsaboya Thanks for suggesting collaboration on the user guide! That's the spirit!

I've been thinking of moving the content of the user guide (currently PDF) to the Wiki pages of the repository. It's easier to update and others can more easily access the content and even edit. What do you think?

I will start by keeping the same headings and content only with minor changes, then open it to the community.

**Comment by rtsaboya** [comment]
I think that could work.  As soon as the basic structure is set up,  I will try to start adding content,  then. 

Cheers.
