### ISSUE TITLE
My axial map not showing in the layer

### ISSUE THREAD

**Issue by Waniey154** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#138]
Hi Sir,

I wish to generate axial line using your depthmap plugins in qgis which i found really helpful in urban field of study. However, there is a issue coming up to me upon drawing the axial line (.shp) using graph analysis.

1) Why my layer are empty, even though i located the data store in the folder?
[img]http://i.imgur.com/NamTAOS.jpg[/img](url)

Many thanks!

**Comment by jorgegil** [comment]
This problem might be related to the fact that your axial layer was drawn using the default coordinate system, maybe WGS84, which is a geographic coordinate system in degrees, minutes and seconds.
Layers must have a projected CRS, as opposed to geographic CRS, as mentioned in issue #131. This issue could eventually be addressed as described in #126, but at some stage the layer will always have to be converted to a projected CRS if it is to be analysed in depthmapXnet.

Hope this helps.

**Comment by Waniey154** [comment]
Hi sir,


Thank you for your explanation.

However I have few question regarding on the CRS.

How to set it according to projected (x/y in meters) CRS? for example in my
case Kertau RSO?

Whenever I tried to set my axial with the CRS (Kertau RSO in my case since
I am living in Malaysia) it went missing same goes to the openstreet map.


​

What is the technique that I could do to make it stay? Can I save the image
from the openstreetmap layer and then digitize the axial map? It is proper?


Many Thanks.


Warm regards,

On Tue, May 31, 2016 at 5:16 AM, Jorge Gil <notifications@github.com> wrote:

> This problem might be related to the fact that your axial layer was drawn
> using the default coordinate system, maybe WGS84, which is a geographic
> coordinate system in degrees, minutes and seconds.
> Layers must have a projected CRS, as opposed to geographic CRS, as
> mentioned in issue #131
> <https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/issues/131>.
> This issue could eventually be addressed as described in #126
> <https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/issues/126>, but
> at some stage the layer will always have to be converted to a projected CRS
> if it is to be analysed in depthmapXnet.
>
> Hope this helps.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/issues/138#issuecomment-222555591>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANc1iFppFVvZd80RblaiyNDigO30iow3ks5qG1PJgaJpZM4IpeWP>
> .
>



-- 
Nur Syazwani Saari
Research Assistant
B.U.R.P (Hons), Master Candidate
UTM-Low Carbon Asia Research Centre
Level 2, Block B-12,
Faculty of Built Environment
Universiti Teknologi Malaysia (UTM)
81310 Johor Bahru, Johor Malaysia

Email :nsyazwanisaari@gmail.com
Contact: +6019-4320081

**Comment by jorgegil** [comment]
- To change the CRS of a layer you need to right click the layer, "Save As...", and choose a projected CRS, in your case Kertau (RSO) EPSG:3168. Then open and work with this new file.
- If you simply set the CRS it goes missing because what you're doing is indicating what CRS the layer is in, not changing it.
- To work with layers in different projections you need to enable 'on-the-fly' CRS transformation. (EPSG button on the bottom right corner).
- This way you can have the live OSM background, and draw your axial map on top in the Kertau CRS. Don't save the OSM layer as an image.

Details on all these topics can be found in the QGIS on-line documentation.

For similar questions that are not issues with the plug-in, but rather the workflow of working with QGIS, I invite you to subscribe and send an email to the mailing list:
- To subscribe: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=SPACESYNTAX-TOOLKIT
- To email: spacesyntax-toolkit@jiscmail.ac.uk

**Comment by Waniey154** [comment]
Hi Sir Jorge,


I tried to post message under JISCMAIL but I am not authorised to do that.

On Fri, Jun 3, 2016 at 6:30 PM, Jorge Gil <notifications@github.com> wrote:

> Closed #138
> <https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/issues/138>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/issues/138#event-680965945>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANc1iIsgnwijXE15fN7mY8y5nGuwSbHDks5qIAJGgaJpZM4IpeWP>
> .
>



-- 
Nur Syazwani Saari
Research Assistant
B.U.R.P (Hons), Master Candidate
UTM-Low Carbon Asia Research Centre
Level 2, Block B-12,
Faculty of Built Environment
Universiti Teknologi Malaysia (UTM)
81310 Johor Bahru, Johor Malaysia

Email :nsyazwanisaari@gmail.com
Contact: +6019-4320081

**Comment by jorgegil** [comment]
After registering, and receiving the approval confirmation, you should be able to post messages to the mailing list.
