### ISSUE TITLE
pyspatialite missing

### ISSUE THREAD

**Issue by jorgegil** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#139]
After upgrading to QGIS 2.16.1, there's an error message saying "No module named pyspatialite". SST does not load after this.
This happens on Mac OSX, kyngchaos release. Not sure about other OS.

It might be possible to install pyspatialite separately. Must check if it is really missing, or has been replaced.

One solution is to re-install version 2.14 LTR. It's possible to have both versions running. User can use 2.14 for the SST and 2.16 if he/she needs specific new features.

**Comment by rtsaboya** [comment]
Didn't have any issues in Windows, for what it's worth.

**Comment by jorgegil** [comment]
Thanks for the confirmation that it works on Windows.

I have found that the problem only occurs on Mac OSX, with the Kyngchaos QGIS distribution. This stackexchange post offers the solution:
https://gis.stackexchange.com/questions/216848/pyspatialite-installation-error-on-macosx-qgis-plugin

There's a folder under the sqlite3 framework that needs to be renamed:
"Library/SQLite3.framework/Versions/C/Python/2.5" rename to "Library/SQLite3.framework/Versions/C/Python/**2.7**"
