### ISSUE TITLE
Values LEN and MD are exchanged in axial analysis [Mac OSX]

### ISSUE THREAD

**Issue by maurimartins** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#143]
Sometimes, the columns LEN and MD are exchanged, affecting results in another measures.  This has been observed in axial analysis (SST 0.1.5, QGIS 2.14.3, GDAL/OGR 1.11.4 for Mac OSX 10.11.16 El Captain).

I can not always reproduce this error. All the three maps were verified with SST "Verify" option.  Two from three different tested maps presented the error.  Would any subtle flaw in linear representation have been misinterpreted by the algorithm, inducing a  bug? 

I intend to observe more, I'll send you news if I find some error pattern.

Meanwhile, it is recommended that  Mac OSX users check the LEN values after run axial analysis.

**Comment by jorgegil** [comment]
Could you please send me a copy of the three files that you used for input and output?
Especially if they consistently give the reported error.

**Comment by jorgegil** [comment]
The issue has now been fixed and will be available in the next release.
If someone needs a "patch", you can get the `DepthmapAnalysis.py` file from the latest source and update it in the .qgis2/python/plugins/esstoolkit/analysis folder.
