### ISSUE TITLE
can't setup plugin SpaceSyntax Toolkit for QGis 

### ISSUE THREAD

**Issue by arteria05** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#163]
Hello!! I set up QGis, but can't setup plugin SpaceSyntax Toolkit. There is a mistake Couldn't load plugin 'esstoolkit' due to an error when calling its classFactory() method . Don't know , what to do, help, please!!)))

**Comment by arteria05** [comment]
Couldn't load plugin 'esstoolkit' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'EssToolkit' 
Traceback (most recent call last):
  File "E:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/1/.qgis3/python/plugins\esstoolkit\__init__.py", line 27, in classFactory
    from EssToolkit import EssToolkit
  File "E:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'EssToolkit'


Версия Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Версия: 2.99.0-Master Master, 1693873 

Расположение Python:
E:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing
E:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/1/.qgis3/python
C:/Users/1/.qgis3/python/plugins
E:/OSGEO4~1/apps/qgis-dev/./python/plugins
E:\OSGeo4W64\bin\python36.zip
E:\OSGEO4~1\apps\Python36\DLLs
E:\OSGEO4~1\apps\Python36\lib
E:\OSGeo4W64\bin
E:\OSGEO4~1\apps\Python36
E:\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/1/.qgis3//python
C:/Users/1/.qgis3/python/plugins\NNJoin

**Comment by arteria05** [comment]
![screen shot 07-11-17 at 05 56 pm](https://user-images.githubusercontent.com/30080234/28074718-f272c196-6661-11e7-8f5b-4d2e2bdba7c4.PNG)

**Comment by jorgegil** [comment]
From the error messages and screenshots it appears your python is version 3.6. Not sure what version of QGIS you are using (is it 2.99?). But the plugin is definitely for python 2.7 and won't work on Python 3.

Python 2.7 is the base python of QGIS 2.14 and 2.18, and the plugin has been tested and works on QGIS rom 2.0 to 2.18.
