### ISSUE TITLE
Cant install plugin

### ISSUE THREAD

**Issue by rsolinis** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#173]
Hello,

I am having troubles at the very first step of using the toolkit. I am trying to follow your instructions but I just cannot install the plugin at all.

I am using a win 7 OS, with qgis Madeira 3.4.4
I have also downloaded depthmapX 0.6.0_win64  (but I am not sure if I have to also install a plug in for it, in any case I cannot install it "cannot load plugin .moc" from the zip folder)
I am using the qgisSpaceSyntaxToolkit-master folder

1. When I search inside plugin manager search bar, SpaceSyntax toolkit does NOT show up. I tried refreshing the plugin repository and check-in boxes for experimental plugins, but no way to find it.
2. I tried installing the SS plug in from the zip folder and I get an error message: "The plugin is broken: missing metadata". And thus, toolkit does not show up in vector tools.
3. I also tried copy-paste esstoolkit folder into: C:\users\USERNAME\.qgis2\python\plugins --- no luck
4. I just cannot find any help or information on how to install the plug in. What I am doing wrong?

I appreciate your help,
Gracias

**Comment by jorgegil** [comment]
The SST plugin currently only exists for version 2.18 of QGIS. There is no schedule yet for upgrading it to QGIS 3. Maybe sometime later in the year... See issue #170.

In the mean time, your best option is to install QGIS 2.18, as both can coexist.

The best way to install is using the Plugins Manager, indeed. And the version of depthmapX you need is called depthmapXnet:
http://archtech.gr/varoudis/depthmapX/?dir=depthmapXnet
