### ISSUE TITLE
Getting the same results of centrality measurements for different radius

### ISSUE THREAD

**Issue by rizkyaj** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#174]
Hi,

I am still new on centrality measurement and also using grass gis with space syntax plugin along with depth map.

Actually, the first problem that I encounter was that using the plugins the Bandung road network osm file that I have cannot be selected for analysis in QGIS. I manage to get around this by changing the file to mif file so that it can be opened directly on depthmap. However, the results of centrality measurements came out with the same results for a different metric radius. I managed to get expected results when using the sample file from space syntax toolkit. 

Some additional information is that the Bandung road network map covers the whole road network in the city of Bandung, Indonesia which much bigger than the sample map from the toolkit.

Is there anyone may have the same experience? and know how to solve such this problem? is depthmap has a certain limitation on the size of the map that can be analyzed? Your insight on this matter is much appreciated.

Regards, 
Rizky

**Comment by jorgegil** [comment]
This is simply to do with the coordinate system of the data being world coordinates. Please re-project to a local coordinate system:
https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/wiki/My-axial-map-layer-doesn't-appear-listed-in-the-axial-map-drop-down-menu

Also for getting help from others I suggest you register for the mailing list and post there instead.
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=SPACESYNTAX-TOOLKIT

Footnote: MIF "worked" but Depthmap interprets the numbers wrong, i.e. degrees are used as meters. Depthmap needs the conversion to x/y in meters.

**Comment by rizkyaj** [comment]
Hi Jorge,

Thank you for the help. I will try to do that and register also for further help inquiries.

With best regards
Rizky Adelwin J

Get BlueMail for Android<http://www.bluemail.me/r?b=14562>
On Mar 13, 2019, at 15:05, Jorge Gil <notifications@github.com<mailto:notifications@github.com>> wrote:

This is simply to do with the coordinate system of the data being world coordinates. Please re-project to a local coordinate system:
https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/wiki/My-axial-map-layer-doesn't-appear-listed-in-the-axial-map-drop-down-menu

Also for getting help from others I suggest you register for the mailing list and post there instead.
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=SPACESYNTAX-TOOLKIT

Footnote: MIF "worked" but Depthmap interprets the numbers wrong, i.e. degrees are used as meters. Depthmap needs the conversion to x/y in meters.
