### ISSUE TITLE
how to run in ubuntu?

### ISSUE THREAD

**Issue by 300000kms** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#178]
I'm trying to run the plugin in ubuntu without succes. For depthmapx we are using the last appimage released and for the plugin in a 2.18 version of qgis.
We are not able to establish the connection. I don't know if perhaps we need to make an specific configuration for linux enviroment?
Thanks!

**Comment by jorgegil** [comment]
QgisToolkit does not use the latest depthmapX but rather depthmapXnet, with a different type of connection. As far as I know there is no Linux version.
http://archtech.gr/varoudis/depthmapX/?dir=depthmapXnet

You can contact the depthmapX mailing list and ask if such a version exists, or any updates are planned.

**Comment by 300000kms** [comment]
thanks Jorge!
