### ISSUE TITLE
Installation issue: SST not shown in plugin manager

### ISSUE THREAD

**Issue by wlien** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#179]
Hello All, 

I am new to Qgis3 and was trying to install SST plugin to Qgis. It was not in the search, "all", or "not installed".  anyone know ways to workaround? thanks

----

so this was answered in previous "issues" that QGIS has not yet loaded with SST. Thank you all

**Comment by Anafi** [comment]
@wlien The Toolkit only works in QGIS version 2. Please install an older version of QGIS. I would recommend 2.18.
