### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by mohdalattar** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#180]
Hi all, 

I've executed axial analysis using DepthMapX remote (QGIS v 2.18.15 / macOS Mojave v 10.14.6 ). However there is some messing features as shown below. 

input data (number of features 49273)
<img width="962" alt="Screenshot 2019-09-30 at 10 43 04" src="https://user-images.githubusercontent.com/50058721/65867908-2699cf00-e36f-11e9-8ff2-b36ec08d43ab.png">

output data  (number of features 45748)
<img width="1008" alt="Screenshot 2019-09-30 at 10 42 17" src="https://user-images.githubusercontent.com/50058721/65867895-226db180-e36f-11e9-9ac1-59c63d80b8e5.png">

Any idea how to include all the features in the analysis ?

**Comment by Anafi** [comment]
@mohdalattar To perform axial analysis you need an axial map. It seems that your input is a segment map or RCL map, is that right?

**Comment by mohdalattar** [comment]
That is correct, it is a road centre line map. Will ticking on "Segment Map or road centre line" solve the problem ?

**Comment by Anafi** [comment]
@mohdalattar To analyse a RCL map, you first need to clean the map using the RCL Cleaner plugin in the SpaceSyntaxToolkit. Then apply the QGIS Simplify Geometries algorithm to simplify angular changes. Some cases may need to be simplified manually, for example parallel lines and traffic details. Then you can use segment analysis and tick "Segment map or road centre line map" to process your map.

**Comment by jorgegil** [comment]
@mohdalattar All the recommendations from @Anafi are indeed necessary to produce a quality model and reliable results.
Besides that, the error that you see, has to do with the fact that you did not check the “Segment map or road centre line map” box. In that case, an axial map is assumed, and only the first segment of each poly line is taken, resulting in all those gaps.
So, for a quick fix simply check the box. For best results follow @Anafi ’s advice.
