### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by cidata-github** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#182]
It does not show up in the Plugin Manager list. When trying to install from the ZIP file, it pops up the error:

Impossível carregar complemento 'esstoolkit' Devido a um erro ao chamar o método Class Factory(). 

ModuleNotFoundError: No module named 'EssToolkit' 
Traceback (most recent call last):
  File "D:/Program Files/QGIS 3.12/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\esstoolkit\__init__.py", line 27, in classFactory
    from EssToolkit import EssToolkit
  File "D:/Program Files/QGIS 3.12/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'EssToolkit'

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versão do QGIS: 3.12.0-București București, cd141490ec 

Caminho do Python:
D:/Program Files/QGIS 3.12/apps/qgis/./python
C:/Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Program Files/QGIS 3.12/apps/qgis/./python/plugins
D:\Program Files\QGIS 3.12\apps\Python37
D:\Program Files\QGIS 3.12\apps\Python37\Scripts
D:\Program Files\QGIS 3.12\bin\python37.zip
D:\Program Files\QGIS 3.12\apps\Python37\DLLs
D:\Program Files\QGIS 3.12\apps\Python37\lib
D:\Program Files\QGIS 3.12\bin
D:\Program Files\QGIS 3.12\apps\Python37\lib\site-packages
D:\Program Files\QGIS 3.12\apps\Python37\lib\site-packages\win32
D:\Program Files\QGIS 3.12\apps\Python37\lib\site-packages\win32\lib
D:\Program Files\QGIS 3.12\apps\Python37\lib\site-packages\Pythonwin
C:/Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tuflow
C:\Users\f\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow
C:\Users\f\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow/forms
C:\Users\f\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow
C:\Users\f\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow
C:\Users\f\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tuflow\tuflowqgis_tuviewer
C:\Program Files\JetBrains\PyCharm 2019.2\debug-eggs
C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev
C:\Program Files\JetBrains\PyCharm 2019.1.3\debug-eggs
C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev

**Comment by telmovdomingues** [comment]
As far as I know, 'esstoolkit'  isn't optimized yet to work with QGIS 3.12, only v2.18.x, so my sugestion is install the last 2.18 version.

Installing the plugin by extracting the file, the correct is "C:\Users\<username>\.qgis2\python\plugins\"

**Comment by jorgegil** [comment]
That is correct, the current version only works on QGIS2. There the plugin will show up in the plugins manager list and this is the recommended method for installation.
About an upgrade to QGIS3, it's something being currently discussed.
