### ISSUE TITLE
Unlink layer fails to export in Graph Analysis

### ISSUE THREAD

**Issue by tantoon94** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#187]
when I try to update ID and verify the unlink layers in the graph analysis step, there is a message saying: "The axial layer has invalid or duplicate values in the id column. Using feature ids instead." after this when I want to analyze the verified layers, there pops-up an error stating: "Python error: failed to export unlinks." as a result, the analysis breaks the unlinked lines to segments and then analyze. How can I fix this error?

I am working on Windows Qgis version 2.18 and have double-checked the SS Toolkit installation and updates.

**Comment by jorgegil** [comment]
The first thing I suggest is that you add an ID column to the axial layer with unique numbers. You can add a column called "id" and populate with the row number using the layer attribute tools. If there is an ID column already it must have duplicates or NULL values, so you can update that column, if you're not using those ids for anything else. Then the unlink verification and analysis should work as expected.

Of course, the error should not happen, but it might be that there is a problem with the feature ids. It is known that shape files in QGIS, when they are edited and lines deleted, the resulting file is not completely clean. After a lot of editing, it might be a good idea to create a new shape file using "Save layer as..."

**Comment by tantoon94** [comment]
Thank you Jorge, I did as you said and it was fixed!

**Comment by andreguimar** [comment]
I had the same error mensage, so I updated feature ids and after fix the error.
