### ISSUE TITLE
Glossary of terms and abbreviations

### ISSUE THREAD

**Issue by Intuos5** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#190]
Is there some sort of glossary, documentation or are there research papers available that addresses the specific abbreviations used within the Space Syntax toolkit? I find the 5 letter names quite cryptic despite having read plenty of literature on the subject. For me and other new users, it would be a big help if these could be found more easily from the Github page. 
To give an examples of these abbreviations: INThh, INTpv, INTtk, INTEN, NC, ra, ra[penn] rra, reIENT and CH.

Would it perhaps be possible to adopt the Geopackage file format so that the full names could be used instead of the abbreviations (due to shapefile character restrictions)? But for now any help on the naming would already be sufficient.

**Comment by pklampros** [comment]
Hey @Intuos5, what you have there is the metrics calculated from depthmapX, as they are passed through [a replacement table](https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/blob/d62e757d55ca00353d766fe9a7a21ba00f958a5d/esstoolkit/analysis/DepthmapEngine.py#L167). You can get the metrics by opening a map in depthmapX and carrying out axial analysis with all options selected:

Ref
Choice
Choice [Connectivity Wgt]
Choice [Connectivity Wgt][Norm]
Choice [Norm]
Connectivity
Control
Controllability
Entropy
Harmonic Mean Depth
Integration [HH]
Integration [P-value]
Integration [Tekl]
Intensity
Line Length
Mean Depth
Mean Depth [Connectivity Wgt]
Node Count
RA
RA [Penn]
RRA
Relativised Entropy
Total Connectivity
Total Depth

**Comment by Intuos5** [comment]
Thanks!
