### ISSUE TITLE
Keep Attributes while running analysis

### ISSUE THREAD

**Issue by deepthijhn** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#192]
Unable to keep attributes of layer while running analysis, similar to Depthmap 0.5

**Comment by jorgegil** [comment]
Can you please provide further details of the issue? What is the specific case and need?

I would argue that this is an intended feature. The analysis results, depending on the number of selected radii, can return in a very long list of attributes.

The main attribute that is kept from the input table is the ID of the original features. Being in a GIS environment, making a join between tables to obtain the complete set of attributes is pretty straightforward.

**Comment by deepthijhn** [comment]
Thank you. I have existing information on the lines that I want to use to compare with the analysed values. The IDs were not matching with the analysed files to join them, however, might have been an error on my part, where i might have updated IDs.

**Comment by jorgegil** [comment]
I've just done some quick tests.

The existing ID column values are transfered to the column "axid" when you run axial or segment analysis from an axial map.

If you start from an already segmented map, then the original is is in the column "segid".

If you start from road centre lline, the field "segid" contains the rowid of the original map.

Hope this helps.
