### ISSUE TITLE
Feature request: Support CUDA framework

### ISSUE THREAD

**Issue by Intuos5** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#201]
It would be great to have CUDA support so that the GPU can be leveraged for the calculations as opposed to the CPU. This should increase calculation speeds with an Nvidia GPU. The Decoding Spaces Toolbox (see: https://toolbox.decodingspaces.net/#aboutToolbox) does this for their Rhino (Grasshopper) plugin and this leads to significant speedups when enabled.

**Comment by e-kotov** [comment]
I really doubt this is possible, since qgisSpaceSyntaxToolkit just calls on console depthmapX which itself is not even using multiple CPU processes. You may be better off using PlaceSyntaxToole by SMoG - it is multiprocessor compatible and speeds up the calculations significantly.

**Comment by jorgegil** [comment]
@Intuos5 indeed this is not possible with the SST in its current form, as @e-kotov explains.
