### ISSUE TITLE
Conflict resulting from dependencies on external libraries

### ISSUE THREAD

**Issue by laurensversluis** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#96]
Some issues occurred when installing the external libraries needed for the complete functionality of the ESS tool. Libraries were linked to wrong Python.

**Comment by jorgegil** [comment]
This is to me one of the biggest challenges in making user friendly plugins for QGIS. The dependency on external packages raises the bar in terms of Python installation and management (issue #63). But external packages can be extremely useful.
There are some steps to minimise the problem:
* Creating detailed installation instruction for the different platforms (issue #69).
* Checking if they are available and let the tool run (with reduced functionality).
* Incorporating some important packages in the QGIS distribution in the future.

**Comment by jorgegil** [comment]
The packages are now included locally in the SST distribution, without the need for installation. It has been addressed with issue #63.
This problem should not occur any more, but it's important to test this solution on more systems to see if there are other conflicts or problems.
