### ISSUE TITLE
Processing fails when using certain projections

### ISSUE THREAD

**Issue by laurensversluis** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#97]

**Comment by jorgegil** [comment]
Which ones in particular, for testing purposes?
Processing requires projected coordinate systems, and not World coordinate systems. Must do a check if the layer has the correct type of CRS.

**Comment by laurensversluis** [comment]
Hello! This happened once so dont take it so seriously. We had a model with a SRID 4326 which was not selectable from the datastore. When we transformed it to UTM it worked.

**Comment by jorgegil** [comment]
Ah, 4326 is WGS84, which is a geographic CRS, therefore those layers don't show up in the layers list for processing in "Graph Analysis".
WGS84 is the default CRS in QGIS and the one many people end up using when they start creating layers from scratch.
